### ISSUE TITLE
prices should also return currency

### ISSUE THREAD

**Issue by iranzo** [sergioteula/python-amazon-paapi5#1]
Hi,
Prices seems to return pvp and price, but not currency (but it is returned in offers).

For consistency, there should be a product.prices.currency

Thanks

**Comment by sergioteula** [comment]
Thanks for the comment, support for currency has already been added. You can upgrade by using:
`pip install python-amazon-paapi5 --upgrade`

**Comment by iranzo** [comment]
Thanks!
