### ISSUE TITLE
Multiple ASINs in the same request

### ISSUE THREAD

**Issue by migcm** [sergioteula/python-amazon-paapi5#2]
Don't have support for multiple ASINs in the same API request?

**Comment by sergioteula** [comment]
Not yet, but I'm working on it for the next release (it should be soon). Thanks!

**Comment by sergioteula** [comment]
This is already added, you can upgrade with `pip install python-amazon-paapi5 --upgrade`.

**Comment by migcm** [comment]
Thank you! =)
